# Generated by Django 2.2.1 on 2019-05-30 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AddField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(to='expenses.Category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
