# Generated by Django 2.2.4 on 2019-09-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20190829_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Location'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Source'),
        ),
    ]
