# Generated by Django 2.2.1 on 2019-05-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20190530_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(blank=True, to='expenses.Category'),
        ),
    ]
