# Generated by Django 2.2.1 on 2019-06-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20190609_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='location',
            new_name='locations',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='source',
            new_name='sources',
        ),
    ]
