# Generated by Django 2.2.2 on 2019-06-29 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20190628_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='UserData',
        ),
    ]
