# Generated by Django 2.2.5 on 2019-09-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190629_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='primaryField',
            field=models.CharField(choices=[('CATEGORIES', 'Categories'), ('LOCATIONS', 'Locations'), ('SOURCES', 'Sources')], default='CATEGORIES', max_length=10),
        ),
    ]
