export const GET_EXPENSES = 'GET_EXPENSES';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';

export const APP_LOADING = 'APP_LOADING';
export const APP_LOADED = 'APP_LOADED';
export const APP_DATA_FETCHED = 'APP_DATA_FETCHED';

export const USER_LOADED = 'USER_LOADED';
export const USER_UPDATED = 'USER_UPDATED';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGES = 'DELETE_MESSAGES';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';

export const GET_LOCATIONS = 'GET_LOCATIONS';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const EDIT_LOCATION = 'EDIT_LOCATION';
export const ADD_LOCATION = 'ADD_LOCATION';

export const GET_SOURCES = 'GET_SOURCES';
export const DELETE_SOURCE = 'DELETE_SOURCE';
export const EDIT_SOURCE = 'EDIT_SOURCE';
export const ADD_SOURCE = 'ADD_SOURCE';
